SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM products;
SELECT * FROM order_items;

-- 1. Total revenue
-- Business Insight: Shows the Total Revenue generated
SELECT SUM(order_amount) as Total_Revenue FROM orders;

-- 2. Total orders
-- Business Insights: Shows the Total orders placed 
SELECT COUNT(order_id) as Total_Orders FROM orders;

-- 3. Total customers
-- Business Insights: Identifies the No. of Customers 
SELECT COUNT(customer_id) as Total_customers FROM customers;

-- 4. Revenue by category
-- Business Insights: Identifies the Revenue Generated by each product category
-- This is for no discount
SELECT p.category, SUM(p.price * oi.quantity) as Revenue
FROM order_items oi 
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category;
 
-- This is where discounted amount is calculated
WITH OrderSubtotals AS (
    -- Phase 1: Figuring out the "Expected" total for every order before discounts
    SELECT 
        oi.order_id,
        SUM(p.price * oi.quantity) AS expected_cart_value
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
),
ProratedItems AS (
    -- Phase 2: Applying the math formula to find the "True" revenue of each item
    SELECT 
        o.order_id,
        p.category,
        (p.price * oi.quantity) AS raw_item_value,
        ((p.price * oi.quantity) / os.expected_cart_value) * o.order_amount AS true_item_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    JOIN OrderSubtotals os ON o.order_id = os.order_id
)
-- Phase 3: Group by Category and sum up the true prorated revenue
SELECT 
    category,
    ROUND(SUM(true_item_revenue), 2) AS true_category_revenue
FROM ProratedItems
GROUP BY category
ORDER BY true_category_revenue DESC;



-- 4. Top 5 customers by revenue
-- Business insights: Identifies the Top 5 customers who had given more revenue to the company
SELECT c.customer_id, c.name, SUM(o.order_amount) AS Revenue
FROM customers c 
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY SUM(o.order_amount) DESC
LIMIT 5;

-- 5. Monthly revenue trend
-- Business Insights: Identifies the revenue per month generated by a business
SELECT DATE_FORMAT(order_date, '%Y-%m') AS YearMonth, SUM(order_amount) AS Revenue
FROM orders
GROUP BY YearMonth
ORDER BY YearMonth;

-- 6. Average order value
-- Business Insights: Calculates the Average revenue per order
-- Direct Method-
SELECT AVG(order_amount) as Average_Order_Value FROM orders;

-- Mathematical Calculation-
SELECT 
    SUM(order_amount) / COUNT(order_id) AS Avg_Order_Value
FROM orders;

-- 7. Repeat customers (>= 2 orders)
-- Business Insights: Identifies the retained customers
SELECT c.customer_id, c.name, COUNT(o.order_id) AS No_of_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(o.order_id) >= 2;

-- 8. Customers who ordered only once
-- Business Insights: Identifies the churned customers(orderes only once)
SELECT c.customer_id, c.name, COUNT(o.order_id) AS No_of_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(o.order_id) = 1;

-- 9. Retention Rate
-- Business Insight: Calculates the Retention rate of customers 
WITH CustomerOrders AS (
	-- Aggregating total orders per customers
    SELECT 
        customer_id,
        COUNT(order_id) AS order_count
    FROM orders
    GROUP BY customer_id
)
-- Calculating retention rate 
SELECT 
    COUNT(CASE WHEN order_count >= 2 THEN 1 END) * 1.0  -- case for counting regular customers only
    / (SELECT COUNT(*) FROM customers) AS Retention_Rate
FROM CustomerOrders;

-- 10. Top category per month
-- Business Insights: Identifies the product category who had generated highest revenue per month
WITH CategoryRevenue AS (    
	-- Revenue per category per month
	SELECT p.category, DATE_FORMAT(o.order_date, '%Y-%m') AS YearMonth, SUM(p.price * oi.quantity) AS Revenue
	FROM orders o
	INNER JOIN order_items oi ON o.order_id = oi.order_id
	INNER JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.category, YearMonth
), 
Ranking AS (   
	-- Ranking inside each month
	SELECT *, ROW_NUMBER() OVER(PARTITION BY YearMonth
								ORDER BY Revenue DESC) AS rn
	FROM CategoryRevenue
)
SELECT category, YearMonth, Revenue
FROM Ranking
WHERE rn = 1; -- picking top 1 

-- 11. Running Total Revenue(Monthly)
-- Business Insights: Calculates cumulative Rvenue monthly
WITH MonthlyRevenue AS (
	-- Aggregating Total Revenue by Month
    SELECT 
        DATE_FORMAT(order_date, '%Y-%m') AS YearMonth,
        SUM(order_amount) AS Revenue
    FROM orders
    GROUP BY YearMonth
)
-- Applying Window Function To find running revenue
SELECT 
    YearMonth,
    SUM(Revenue) OVER(ORDER BY YearMonth) AS cumulative_revenue
FROM MonthlyRevenue;